# Generated by Django 5.2.17 on 2026-08-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_migrate_user_salary_to_payroll'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyconfig',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companyconfig',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='companylogo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companylogo',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='salary',
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['organization', 'role'], name='accounts_cu_organiz_ad3364_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['organization', 'is_active'], name='accounts_cu_organiz_a4c735_idx'),
        ),
        migrations.DeleteModel(
            name='CompanyConfig',
        ),
        migrations.DeleteModel(
            name='CompanyLogo',
        ),
    ]
