# Generated by Django 5.2.17 on 2026-08-23 05:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # swappable_dependency(AUTH_USER_MODEL) resolves to accounts.__first__, but
    # accounts.0001 creates a model named `User`; `CustomUser` only exists from
    # 0002 onward. Depend on the concrete migration instead.
    dependencies = [
        ("accounts", "0010_companyconfig_bypass_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('departments', models.JSONField(blank=True, default=list)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('employment_types', models.JSONField(blank=True, default=list)),
                ('bypass_attendance', models.BooleanField(default=False, help_text='Pay a full month regardless of recorded attendance.')),
                ('employee_sequence', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organizations', to='accounts.customuser')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
