# Generated by Django 5.2.17 on 2026-08-23 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, default='', help_text="Actor's login id captured at write time, so the entry survives deletion.", max_length=255)),
                ('action', models.CharField(choices=[('SALARY_SET', 'Salary set'), ('EXPENSE_SUBMITTED', 'Expense submitted'), ('EXPENSE_APPROVED', 'Expense approved'), ('EXPENSE_REJECTED', 'Expense rejected'), ('PAYROLL_RUN', 'Payroll run'), ('PAYROLL_CREDITED', 'Payroll credited'), ('LEAVE_APPROVED', 'Leave approved'), ('LEAVE_REJECTED', 'Leave rejected'), ('EMPLOYEE_CREATED', 'Employee created'), ('EMPLOYEE_DEACTIVATED', 'Employee deactivated'), ('EMPLOYEE_REACTIVATED', 'Employee reactivated'), ('SETTINGS_CHANGED', 'Organization settings changed'), ('SUBSCRIPTION_CHANGED', 'Subscription changed')], db_index=True, max_length=32)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_label', models.CharField(blank=True, default='', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system-initiated actions such as Stripe webhooks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_audit_organiz_c1c99d_idx'), models.Index(fields=['organization', 'action', '-created_at'], name='audit_audit_organiz_d65ad8_idx')],
            },
        ),
    ]
